# Generated by Django 4.2.5 on 2023-09-18 06:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_name', models.CharField(max_length=200)),
                ('landuse_class', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
