# Generated by Django 4.2.5 on 2023-09-18 07:03

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'ground_truth.json'

class Migration(migrations.Migration):
    def load_data(apps, scheme_editor):
        Sites = apps.get_model('sites', 'Sites')
        jsonfile = Path(__file__).parents[2]/DATA_FILENAME
        
        with open(str(jsonfile)) as datafile:
            objects = json.load(datafile)
            for obj in objects['features']:
                try:
                    geometry = obj['geometry']
                    geometryCoordinates = geometry['coordinates']
                    geometryType = geometry['type']
                    if geometryType == 'Point':
                        properties = obj['properties']
                        name = properties.get('name')
                        longitude = geometryCoordinates[0]
                        latitude = geometryCoordinates[1]
                        location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                        Sites(name=name, location=location).save()
                except KeyError:
                        pass

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(load_data)
    ]
